version: "3.8"
services:
  springboot-app:
    image: hotel-booking-app
    restart: always
    build: .
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_PORT: 3306
    ports:
      - 8001:8443

    networks:
      - shared_network
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.34
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: booking-app
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - shared_network
networks:
  shared_network:
    driver: bridge



